############################################################# Obtener todos los productos
GET http://localhost:4000/product

############################################################# Obtener todos los productos por categoria [carta, figura, video-juego]
GET http://localhost:4000/product?category=video-juego

############################################################# Obtener un producto por Id
GET http://localhost:4000/product/68c163a662e714a4fb763fd5

############################################################# Agregar un Producto
POST http://localhost:4000/product
Content-Type: application/json

{
   "image": "https://p1.akcdn.net/full/1191447598.electronic-arts-ufc-5-xbox-series-x-s.jpg",
   "title": "UFC 5",
   "description": "Plataforma Xbox Serie X",
   "price": 60000,
   "category": "video-juego"
}

############################################################# Eliminar un producto por Id
DELETE http://localhost:4000/product/68c163a662e714a4fb763fd5

############################################################# Modificar un producto por Id
PUT http://localhost:4000/product/68c0a0fb5a46d1be75595b3d
Content-Type: application/json

{
   "title": "Forza New Horizont",
   "image": "https://m.media-amazon.com/images/I81htlTqEckL_SL1500_.jpg",
   "description": "Plataforma PC | PS5",
   "price": 20000,
   "category": "carrera"
}